### ISSUE TITLE
Sugestão de melhoria.

### ISSUE THREAD

**Issue by DemoTimo** [SouOWendel/shinobi-no-sho#26]
Olá! Estou testando o sistema no Foundry e logo começarei uma mesa, mas infelizmente ainda tenho um monitor pequeno e antigo, mesmo no modo de tela cheia, não consigo visualizar toda a aba de perícias corretamente. Seria possível adicionar uma opção de scroll para facilitar a navegação na aba? igual tem na aba combate, por exemplo.

**Comment by SouOWendel** [comment]
Fiz uma alteração nessa última atualização do sistema (1.12.0) pra solucionar isso, dá uma olhada lá.
